version: '3'
services:
  web:
    image: hacklab/mapasculturais-nginx:latest
    restart: unless-stopped
    volumes:
      - ./src/protected:/var/www/html/protected
      - ./scripts:/var/www/scripts
      - ./compose/config.php:/var/www/html/protected/application/conf/config.php
      - ./compose/config.d:/var/www/html/protected/application/conf/config.d
      - ./compose/local/config.local.php:/var/www/html/protected/application/conf/config.d/z.config.local.php
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/private-files
      - ./docker-data/pcache-cron.log:/var/www/scripts/nohup.out
      - ./tests:/var/www/tests
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - mapasculturais
    links:
      - mapasculturais
      
  mapasculturais:
    build:
      context: ./
      dockerfile: compose/production/Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./src/protected:/var/www/html/protected
      - ./scripts:/var/www/scripts
      - ./compose/config.php:/var/www/html/protected/application/conf/config.php
      - ./compose/config.d:/var/www/html/protected/application/conf/config.d
      - ./compose/local/config.local.php:/var/www/html/protected/application/conf/config.d/z.config.local.php
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/private-files
      - ./docker-data/pcache-cron.log:/var/www/scripts/nohup.out
      - ./tests:/var/www/tests
    links:
      - db
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas

      - APP_LCODE=pt_BR
      - ACTIVE_THEME=Saude
      - APP_MODE=development
      - LOGOUT_URL=https://dev.id.org.br/auth/realms/saude/protocol/openid-connect/logout
      - CLIENT_ID=DigitalSaude
      - CLIENT_SECRET=1085ca2a-ab21-46ef-828d-5fb01b43c918
      - AUTH_ENDPOINT=https://dev.id.org.br/auth/realms/saude/protocol/openid-connect/auth
      - TOKEN_ENDPOINT=https://dev.id.org.br/auth/realms/saude/protocol/openid-connect/token
      - USER_INFO_ENDPOINT=https://dev.id.org.br/auth/realms/saude/protocol/openid-connect/userinfo
      - REDIRECT_URI=http://localhost/autenticacao/keycloak/oauth2callback
      - CEP_TOKEN=1a54ab41e1e7b2cdc6d4d0e4b50ce26d
      - PENDING_PCACHE_RECREATION_INTERVAL=60

    depends_on:
      - db
      
  db:
    image:  mdillon/postgis:10
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
      - POSTGRES_DB_TEST=mapasculturais_test
    ports:
      - "5470:5432"
    volumes:
      - ./compose/local/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      #- ./docker-data/db-data:/var/lib/postgresql/data
      - ./docker-data/postgres:/var/lib/postgresql