replicaCount: 1

image:
  repository: mapas
  tag: dev
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

podAnnotations: {}

mapas:
  appEnv: development
  appDebug: "true"

  database:
    host: "" # uses internal postgresql subchart
    port: 5432
    name: mapas
    user: mapas
    password: ""

  redisCache:
    port: 6379

  mailer:
    transport: "smtp://naoresponda%40cultura.org.br:%5DOwjq%2A4%25cjHJqLD9%40mail.cultura.org.br:465"
    from: "n√£o responda<naoresponda@cultura.org.br>"

  recaptcha:
    siteKey: "6LfU2CEqAAAAACrGVDj6Vw3GF16RbBap1uTUG2aE"
    secret: "6LfU2CEqAAAAAApmAVs3ZDHmCIgdaYEgFanKxNDl"

  buildAssets: "0"
  pendingPcacheRecreationInterval: "60"
  jobsInterval: "60"
  numProcesses: "2"
  mcUpdatesProcesses: "4"
  redirectNotFoundAssetsTo: ""

  extraEnv:
    - name: MAPAS_HTTPS
      value: "true"

postgresql:
  enabled: true
  settings:
    superuser: mapas
    superuserPassword: "mapas"
  userDatabase:
    name: mapas
  storage:
    requestedSize: 1Gi

redis-cache:
  enabled: true
  auth:
    enabled: false
  persistence:
    enabled: false

redis-sessions:
  enabled: true
  auth:
    enabled: false
  persistence:
    enabled: true
    size: 1Gi

persistence:
  assets:
    enabled: true
    size: 1Gi
  publicFiles:
    enabled: true
    size: 1Gi
  privateFiles:
    enabled: true
    size: 1Gi
  varFiles:
    enabled: true
    size: 1Gi

ingress:
  enabled: true
  className: traefik
  baseDomain: "mapas.tec.br"
  hosts: null
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
